### ISSUE TITLE
Failed when test bean with an inner class.

### ISSUE THREAD

**Issue by IAmFQQ** [rlogiacco/SmartUnit#7]
hi, Roberto, I have encountered a problem when test a bean with an inner class. 
Stack trace:
java.lang.NoSuchMethodException: com.test.PropertiesTesterTest$AccessInfo.<init>()
	at java.lang.Class.getConstructor0(Class.java:2892)
	at java.lang.Class.getDeclaredConstructor(Class.java:2058)
	at org.agileware.test.AbstractTester.getInstance(AbstractTester.java:306)
	at org.agileware.test.PropertiesTester.testAll(PropertiesTester.java:158)
	at org.agileware.test.PropertiesTester.testAll(PropertiesTester.java:138)
	at com.test.PropertiesTesterTest.testClass(PropertiesTesterTest.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```
public class PropertiesTesterTest {

    @Test
    public void testClass() throws Exception {
        PropertiesTester tester = new PropertiesTester();
        tester.testAll(AccessInfo.class);
    }
    
}
public class AccessInfo{
	private TokenInfo tokenInfo;

	public TokenInfo getTokenInfo() {
		return tokenInfo;
	}

	public void setTokenInfo(TokenInfo tokenInfo) {
		this.tokenInfo = tokenInfo;
	}
    public class TokenInfo{
    	private String password;
    	private String userName;
		public String getPassword() {
			return password;
		}
		public void setPassword(String password) {
			this.password = password;
		}
		public String getUserName() {
			return userName;
		}
		public void setUserName(String userName) {
			this.userName = userName;
		}
    	
    }
}
```

jdk 1.7
smartunit-0.10.1

**Comment by rlogiacco** [comment]
The problem is you are testing a non-static inner class and SmartUnit doesn't know how to build an instance of it for testing.
This can be simply solved instructing SmartUnit on how an instance of `TokenInfo` can be built:

```java
PropertiesTester tester = new PropertiesTester();	
tester.addMapping(AccessInfo.TokenInfo.class, new ValueBuilder<AccessInfo.TokenInfo>() {	
	public AccessInfo.TokenInfobuild() {
		return new AccessInfo().new TokenInfo();
	}
});
tester.testAll(AccessInfo.TokenInfo.class);
```

**Comment by IAmFQQ** [comment]
@rlogiacco Thank you very much. It's work!
